server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/momentours
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/momentours
    username: handjava
    password: handjava

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    com:
      myhandjava:
        momentours: debug

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}